# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/imageregistrationhelper',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/imageregistrationhelper',
                'lib_path': 'imageregistrationhelper'},
  'syms': {'imageregistrationhelper.core': {'imageregistrationhelper.core.foo': ('core.html#foo', 'imageregistrationhelper/core.py')}}}
