# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/imageregistrationhelper',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/imageregistrationhelper',
                'lib_path': 'imageregistrationhelper'},
  'syms': { 'imageregistrationhelper.imreg': { 'imageregistrationhelper.imreg.hello': ( 'image-registration.html#hello',
                                                                                        'imageregistrationhelper/imreg.py')}}}
