# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/imageregistrationhelper',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/imageregistrationhelper',
                'lib_path': 'imageregistrationhelper'},
  'syms': { 'imageregistrationhelper.imreg': { 'imageregistrationhelper.imreg.ImageRegistrationHelper': ( 'image-registration.html#imageregistrationhelper',
                                                                                                          'imageregistrationhelper/imreg.py'),
                                               'imageregistrationhelper.imreg.ImageRegistrationHelper.__init__': ( 'image-registration.html#imageregistrationhelper.__init__',
                                                                                                                   'imageregistrationhelper/imreg.py'),
                                               'imageregistrationhelper.imreg.ImageRegistrationHelper.get_points': ( 'image-registration.html#imageregistrationhelper.get_points',
                                                                                                                     'imageregistrationhelper/imreg.py'),
                                               'imageregistrationhelper.imreg.ImageRegistrationHelper.save': ( 'image-registration.html#imageregistrationhelper.save',
                                                                                                               'imageregistrationhelper/imreg.py'),
                                               'imageregistrationhelper.imreg.ImageRegistrationHelper.warp': ( 'image-registration.html#imageregistrationhelper.warp',
                                                                                                               'imageregistrationhelper/imreg.py'),
                                               'imageregistrationhelper.imreg.warp': ( 'image-registration.html#warp',
                                                                                       'imageregistrationhelper/imreg.py')}}}
