"""Drag your markers and warp"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/10_image-registration.ipynb.

# %% auto #0
__all__ = ['ImageRegistrationHelper', 'warp']

# %% ../notebooks/10_image-registration.ipynb #2519a696-fae1-496e-879c-68cb38f93354
import holoviews as hv 
from holoviews.operation.datashader import rasterize
from holoviews import opts, streams 
from holoviews.streams import PointDraw 

#import panel as pn 

#import skimage.exposure as ske
#import imageio.v2 as io 

import numpy as np 
import re 
import cv2 

import matplotlib.pyplot as plt

# %% ../notebooks/10_image-registration.ipynb #fc58da74
class ImageRegistrationHelper(): 

    def __init__(self, im_src, im_dst, frame_width=400): 
        '''Create interactive holoviews canvas to draw 4 point pairs. '''

        self.im_src = im_src
        self.im_dst = im_dst 
 
        opts.defaults(opts.Points(size=10, line_color='white'), opts.RGB(frame_width=frame_width, frame_height=frame_width, aspect='equal'), opts.Image(frame_width=frame_width, frame_height=frame_width, aspect='equal'))
        
        fill_colors = ['red', 'green', 'orange', 'purple'] 
        H, W = im_src.shape[0:2]
        h, w = im_dst.shape[0:2]
        
        # SOURCE IMAGES x4 
        
        src_maps = []
        src_points = []
        self.src_points_streams = [] 
        src_map_points = []
        
        for i in range(4):     
            src_maps.append(rasterize(hv.RGB(im_src[::-1], kdims=[f'X{i}', f'Y{i}'], bounds=(-0.5, -0.5, W-0.5, H-0.5))).opts(invert_yaxis=True, aspect='equal', frame_width=frame_width, frame_height=frame_width)) 
            src_points.append(hv.Points([]).opts(fill_color=fill_colors[i]))
            self.src_points_streams.append(PointDraw(source=src_points[i], num_objects=1)) 
            src_map_points.append(src_maps[i] * src_points[i]) 
        
        src_row = hv.Layout(src_map_points)
        
        # DESTINATION IMAGES x4 
        
        dst_maps = []
        dst_points = []
        self.dst_points_streams = [] 
        dst_map_points = []
        
        for i in range(4):     
            dst_maps.append(rasterize(hv.RGB(im_dst[::-1], kdims=[f'x{i}', f'y{i}'], bounds=(-0.5, -0.5, w-0.5, h-0.5))).opts(invert_yaxis=True, aspect='equal', frame_width=frame_width, frame_height=frame_width)) 
            dst_points.append(hv.Points([]).opts(fill_color=fill_colors[i]))
            self.dst_points_streams.append(PointDraw(source=dst_points[i], num_objects=1)) 
            dst_map_points.append(dst_maps[i] * dst_points[i]) 
        
        dst_row = hv.Layout(dst_map_points)
        
        self.canvas = (src_row + dst_row).cols(4)  

    def get_points(self): 
        '''Returns numpy arrays with x,y coordinates''' 
    
        # step 1: get dictionaries from streams
        src_point_dicts = [sps.data for sps in self.src_points_streams] 
        dst_point_dicts = [dps.data for dps in self.dst_points_streams] 
    
        # step 2: get arrays with x,y  coordinates for each point
        self.pts_src = np.array([[spd['x'], spd['y']] for spd in src_point_dicts])
        self.pts_dst = np.array([[dpd['x'], dpd['y']] for dpd in dst_point_dicts])
    
        return self.pts_src, self.pts_dst 

    def warp(self, keep_scale=True, rgba=False, alpha_color=[1, 0, 0]): 
        '''Compute high resolution homeography image and extent.''' 

        self.get_points()
        
        h, w = self.im_dst.shape[0:2]
    
        self.imvis_reg_highres, self.extent = warp(self.im_src, self.im_dst, self.pts_src, self.pts_dst, keep_scale=keep_scale, rgba=rgba, alpha_color=alpha_color) 

        left = rasterize(hv.RGB(self.imvis_reg_highres, bounds=(-0.5, -0.5, w-0.5, h-0.5)).opts(aspect='equal'))
        right = rasterize(hv.RGB(self.im_dst, bounds=(-0.5, -0.5, w-0.5, h-0.5)).opts(aspect='equal'))
        
        return left + right 

    def save(self, fname=None): 
        '''Save registered image to file `fname`.
        
        Returns: imvis_reg_highres, extent.
        '''
        

        if fname is not None: 
            
            plt.imsave(fname, self.imvis_reg_highres)

        return self.imvis_reg_highres, self.extent


def warp(im_src, im_dst, pts_src, pts_dst, keep_scale=True, rgba=True, alpha_color=[1, 0, 0]): 
    '''Opencv based homographic registration. Can return transparent overlay (rgba). 
    
    Returns: *im_warped*, *extent* '''

    src_h, src_w = im_src.shape[0:2]
    dst_h, dst_w = im_dst.shape[0:2]
    
    if keep_scale: 
        scale = src_h / dst_h 
    else: 
        scale = 1

    # calculate homography 
    pts_src = np.array(pts_src)
    pts_dst = np.array(pts_dst)
    hom, status = cv2.findHomography(pts_src, scale * pts_dst)

    # Size is nearest integer scaled (width,height) of im_dst
    size = round(scale * dst_w), round(scale * dst_h)
    
    # warp im_src onto destination 
    im_warped = cv2.warpPerspective(im_src, hom, size) 
    
    # warp white onto destination to create mask 
    mask_src = np.ones([src_h, src_w])
    mask_warped = cv2.warpPerspective(mask_src, hom, size) 
    
    # calculate extent for plotting 
    h, w = im_dst.shape[0:2] 
    extent =  (0, w, h, 0) 
    
    # convert into rgba image  
    if rgba is True: 
        im_rgba = np.ones([h, w, 4])

        # for single channel image 
        if len(im_src.shape) == 2:
            # colorize
            im_rgba[:,:,0:3] = alpha_color[0:3] 
            #  make alpha layer 
            im_rgba[:,:,3] = im_warped 
            
        # otherwise assume image is rgb
        elif len(im_warped.shape) == 3: 
            
            # rgb channels
            im_rgba[:,:,0:3] = im_warped[:,:,0:3]
            # alpha channels 
            im_rgba[:,:,3] = mask_warped
       
        im_warped = im_rgba 
    
    return im_warped, extent  

