"""Your first homography"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/10_image-registration.ipynb.

# %% auto 0
__all__ = ['hello']

# %% ../notebooks/10_image-registration.ipynb 3
def hello(): 
    print('hi!')
